import numpy as np
import numpy.typing as npt
from typing import List, Tuple, Optional, Any, Dict

class InferenceResult:
    mean_effect: float
    predictions: npt.NDArray[np.float64]
    confidence_intervals: List[Tuple[float, float]]
    feature_importance: List[float]
    def summary(self) -> str: ...
    def to_visual_tag(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def show(self) -> None: ...
    def preview(self) -> None: ...

class ValidationResult:
    is_robust: bool
    message: str

class Model:
    def estimate_effects(self, x: npt.NDArray[np.float64]) -> InferenceResult: ...
    def validate(self, n_folds: int = 5, is_time_series: bool = False) -> ValidationResult: ...
    def plot_importance(self) -> None: ...
    def plot_effects(self) -> None: ...
    def to_visual_tag(self, plot_type: str = "graph") -> str: ...
    def show(self, plot_type: str = "graph") -> None: ...
    def preview(self, plot_type: str = "graph") -> None: ...

def create_model(
    features: npt.NDArray[np.float64],
    treatment: npt.NDArray[np.float64],
    outcome: npt.NDArray[np.float64],
    feature_names: Optional[List[str]] = None
) -> Model: ...

def plot_model(model: Model, plot: str = "graph") -> Dict[str, Any]: ...

def analyze_flow() -> str: ...
